version: '3'
services:
  app:
    build: .
    image: ${DOCKER_USER_ID}/flask
  production:
    image: ${DOCKER_USER_ID}/flask:${BUILD_NUMBER}
    context: .
    dockerfile: ./Dockerfile
    command: python3 app.py
    volumes:
      - .:/code
    ports:
      - "80:80"
